project:
  type: book

book:
  title: "CK010 <br> Course pack </br> "
  author: "Jeremy Labrecque"
  page-footer:
    right: 
      - text: "Last updated: 14-11-2025"
  chapters:
    - index.qmd
    - 01-why.qmd
    - 02-notation.qmd
    - 02-q-before a.qmd
    - 03-confounding.qmd
    - 04-a whirlwind tour.qmd
    - 05-statistical significance is useless.qmd
    - 06-Regression is only the beginning.qmd
    - 07-uncertainty.qmd
    - references.qmd

bibliography: /Users/jeremylabrecque/epidemiology/zotero/zotero.bib

format:
  html:
    theme: cosmo
    grid:
      margin-width: 350px
  pdf:
    documentclass: scrreprt
reference-location: margin
citation-location: margin

editor: visual

